"""empty message

Revision ID: 07ccce5bddc3
Revises: 40679a1eda5d
Create Date: 2021-05-14 11:30:02.371339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ccce5bddc3'
down_revision = '40679a1eda5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benchmark_task', sa.Column('buildOutput', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('benchmark_task', 'buildOutput')
    # ### end Alembic commands ###
