"""empty message

Revision ID: 6e83ce29421f
Revises: 
Create Date: 2021-04-22 13:10:32.026975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e83ce29421f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_suite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=False),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('created', 'pending', 'assigned', 'evaluated', 'cancelled', name='taskstate'), nullable=True),
    sa.Column('assignedAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('assignee', sa.String(length=100), nullable=True),
    sa.Column('exitcode', sa.Integer(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('time', sa.BIGINT(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['suite_id'], ['benchmark_suite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runtime_env',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dockerfile', sa.Text(), nullable=True),
    sa.Column('cpuLimit', sa.Integer(), nullable=True),
    sa.Column('memoryLimit', sa.Integer(), nullable=True),
    sa.Column('timeLimit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['suite_id'], ['benchmark_suite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runtime_param',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('env_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['env_id'], ['runtime_env.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runtime_param')
    op.drop_table('runtime_env')
    op.drop_table('benchmark_task')
    op.drop_table('benchmark_suite')
    # ### end Alembic commands ###
